# Generated by Django 5.0.14 on 2025-08-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
